import { GoogleGenAI, Chat, GenerateContentResponse } from "@google/genai";
import { SYSTEM_INSTRUCTION } from "../constants";

let chatSession: Chat | null = null;
let genAI: GoogleGenAI | null = null;

const getGenAI = () => {
  if (!genAI) {
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
      throw new Error("API_KEY environment variable is missing.");
    }
    genAI = new GoogleGenAI({ apiKey });
  }
  return genAI;
};

export const initializeGemini = (): Chat => {
  if (chatSession) return chatSession;

  const ai = getGenAI();
  
  // Using gemini-2.5-flash for fast, responsive chat interactions
  chatSession = ai.chats.create({
    model: 'gemini-2.5-flash',
    config: {
      systemInstruction: SYSTEM_INSTRUCTION,
      temperature: 0.8,
    },
  });

  return chatSession;
};

export const sendMessageToGemini = async (message: string): Promise<string> => {
  if (!chatSession) {
    initializeGemini();
  }

  if (!chatSession) {
    throw new Error("Failed to initialize Gemini session.");
  }

  try {
    const response: GenerateContentResponse = await chatSession.sendMessage({ message });
    return response.text || "No response generated.";
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const analyzeVideoConcept = async (concept: string): Promise<string> => {
  const ai = getGenAI();
  const model = ai.models;

  const prompt = `
    ACT AS A VIRAL CONTENT ALGORITHM EXPERT.
    Analyze this video concept for TikTok/Reels/Shorts: "${concept}"
    
    RETURN ONLY A RAW TEXT REPORT IN THIS FORMAT:
    
    [SCORE]: <0-100 Number based on retention potential>
    [VERDICT]: <One brutal sentence on why it will fly or flop>
    [HOOK]: <An improved, punchy 3-second hook text overlay>
    [CAPTIONS]:
    1. <Caption option 1>
    2. <Caption option 2>
    3. <Caption option 3>
    [HASHTAGS]: <A stack of 10 relevant, high-volume tags>
    
    BE DIRECT. NO FILLER.
  `;

  try {
    const result = await model.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
    });
    return result.text || "Analysis Failed.";
  } catch (error) {
    console.error("Analysis Error:", error);
    throw error;
  }
};

export const generateMockup = async (modelBase64: string, garmentBase64: string, userPrompt: string): Promise<string> => {
  const ai = getGenAI();
  
  // Helper to strip data URL prefix if present
  const cleanBase64 = (str: string) => str.includes('base64,') ? str.split('base64,')[1] : str;
  const getMimeType = (str: string) => str.includes(':') && str.includes(';') ? str.split(':')[1].split(';')[0] : 'image/png';

  const modelData = cleanBase64(modelBase64);
  const garmentData = cleanBase64(garmentBase64);
  const modelMime = getMimeType(modelBase64);
  const garmentMime = getMimeType(garmentBase64);

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { 
            text: `Generate a high-quality, photorealistic fashion mockup. 
                   Instruction: Put the clothing item shown in the second image onto the model shown in the first image. 
                   Ensure the fit is realistic, respecting the lighting and pose of the model. 
                   ${userPrompt}` 
          },
          { inlineData: { mimeType: modelMime, data: modelData } },
          { inlineData: { mimeType: garmentMime, data: garmentData } },
        ]
      }
    });

    // Iterate to find the image part
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Image Generation Error:", error);
    throw error;
  }
};

export const extendImage = async (imageBase64: string, aspectRatio: string, userPrompt: string): Promise<string> => {
  const ai = getGenAI();
  
  const cleanBase64 = (str: string) => str.includes('base64,') ? str.split('base64,')[1] : str;
  const getMimeType = (str: string) => str.includes(':') && str.includes(';') ? str.split(':')[1].split(';')[0] : 'image/png';

  const imgData = cleanBase64(imageBase64);
  const imgMime = getMimeType(imageBase64);

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { 
            text: `Re-generate this image with the requested aspect ratio. 
                   Maintain the original subject matter exactly, but extend the background realistically to fill the new dimensions (Generative Fill). 
                   Ensure the style, lighting, and textures are seamless and photorealistic.
                   ${userPrompt}` 
          },
          { inlineData: { mimeType: imgMime, data: imgData } },
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as "1:1" | "3:4" | "4:3" | "9:16" | "16:9"
        }
      }
    });

    // Iterate to find the image part
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Image Extension Error:", error);
    throw error;
  }
};